// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh-kxJqvvzyO8BlXnGp7u1izF_OzljpKU',
    appId: '1:79330822727:web:1fcaf3717186f822b77f62',
    messagingSenderId: '79330822727',
    projectId: 'foodapp-1129e',
    authDomain: 'foodapp-1129e.firebaseapp.com',
    storageBucket: 'foodapp-1129e.appspot.com',
    measurementId: 'G-9HYLYXKNR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO8e3VXq21SJ2UUeUvXApMNa5hdxZewP4',
    appId: '1:79330822727:android:884db618fbf16b8fb77f62',
    messagingSenderId: '79330822727',
    projectId: 'foodapp-1129e',
    storageBucket: 'foodapp-1129e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqLxACJUbxEPe5XHnF1S7Ew3zzioVkxas',
    appId: '1:79330822727:ios:e8fd3fcc8c1515b8b77f62',
    messagingSenderId: '79330822727',
    projectId: 'foodapp-1129e',
    storageBucket: 'foodapp-1129e.appspot.com',
    iosClientId: '79330822727-22h9his3jvfsaaks0rtsuacei10bvedn.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqLxACJUbxEPe5XHnF1S7Ew3zzioVkxas',
    appId: '1:79330822727:ios:bb1ad83bcac2f8f8b77f62',
    messagingSenderId: '79330822727',
    projectId: 'foodapp-1129e',
    storageBucket: 'foodapp-1129e.appspot.com',
    iosClientId: '79330822727-mhog10au5m93bu0icbcv0mmnboijm1rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodsApp.RunnerTests',
  );
}
